packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 2"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Capgemini"
    task = "WP09"
  }
  client_id                         = "6aeccb9e-2260-470b-831e-fb83aa222bfb"
  client_cert_path                  = "/home/cis/Desktop/KeyStore Explorer/Packer.pfx"
  client_cert_password              = "k81dgg34l8bgkah797xnq3lh"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "Germany West Central"
  managed_image_name                = "wp09image"
  managed_image_resource_group_name = "wp09"
  os_type                           = "Linux"
  subscription_id                   = "ce43c746-b7df-4b6f-96fd-06c057c5ead5"
  tenant_id                         = "1448af85-068e-49e4-9ae1-6302d13bacfa"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "apt-get update",
      "add-apt-repository main",
      "apt-get upgrade -y",
      "apt-get -y install libopenscap8 unzip",
      "mkdir /oscap",
      "curl -L -O https://github.com/ComplianceAsCode/content/releases/download/v0.1.74/scap-security-guide-0.1.74.zip",
      "unzip scap-security-guide-0.1.74.zip",
      "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation --results-arf cis-benchmark-results.xml --report /oscap/reportbefore.html ./scap-security-guide-0.1.74/ssg-ubuntu2204-ds.xml",
      "oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation --results-arf cis-benchmark-results.xml ./scap-security-guide-0.1.74/ssg-ubuntu2204-ds.xml",
      "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation --results-arf cis-benchmark-results.xml --report /oscap/reportafter.html ./scap-security-guide-0.1.74/ssg-ubuntu2204-ds.xml || true",
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang  = "/bin/sh -x"
  }
}
